version: "2"

linters:
  default: all
  disable:
    - noinlineerr
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/google/uuid
            - github.com/robfig/cron/v3
            - github.com/devem-tech/telegram-bot-platform
    revive:
      rules:
        - name: package-comments
          disabled: true
    varnamelen:
      min-name-length: 2
      ignore-names:
        - x

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/devem-tech/telegram-bot-platform)
